### ISSUE TITLE
cannot execute statement 'update default set default=0 returning default'

### ISSUE THREAD

**Issue by j-larson** [jdbc-json/jdbc-cb#16]
This statement cannot be executed through the driver when running against recent version of Couchbase.

The problem was observed on version 4.5.0-977 Enterprise Edition (build-977).

A snippet of code that reproduces this problem is commented out in StatementTest.simpleInsert().

**Comment by j-larson** [comment]
The statement itself does not make sense, and has no effect.

**Comment by varakur** [comment]
Apparently, the statement should be able to run (following output is with 4.5DP build 1308).  Can you make sure this and other 'update' statements can run properly with the driver.
Reopening for the validation.

thanks,
-Prasad

go_cbq> update default set default=0 returning default;
{
    "requestID": "6c316b3a-d063-46b5-a9fe-d7bcbd01fd0b",
    "signature": {
            "default": "json"
        },
    "results" : [

```
],
"status": "success",
"metrics": {
        "elapsedTime": "8.020655ms",
        "executionTime": "7.995535ms",
        "resultCount": 0,
        "resultSize": 0
    }
```

}
go_cbq>

**Comment by j-larson** [comment]
You want me to check that the driver can execute a statement that doesn’t do anything useful, and is no longer used in the original test?

**Comment by varakur** [comment]
Why do you say it is useless statement? Try any other update statements in similar format.
-Prasad

**Comment by j-larson** [comment]
The test currently uses the very similar, and correctly functioning, statement "Update default set val=0 returning val.".

The test is run as part of "mvn test" and currently passes.
