### ISSUE TITLE
link for prebuilt JARs does not work

### ISSUE THREAD

**Issue by ingenthr** [jdbc-json/jdbc-cb#17]
The README has a link for prebuilt .jar files, but doesn't seem to respond.

**Comment by arun-gupta** [comment]
Duplicate of #15

**Comment by j-larson** [comment]
Yeah, sorry about that. I've removed the link, so other people don't stumble over it.

I'll replace it with instructions for downloading from the Maven Repo when that's available.

**Comment by j-larson** [comment]
Jar is available from Maven Central.
