### ISSUE TITLE
jdbc-cb does not work with any bucket except default or beer-sample

### ISSUE THREAD

**Issue by pm48** [jdbc-json/jdbc-cb#33]
A simple program below:
package com.test.jdbc.test5;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;

/*
This example shows
a) How to run a simple SELECT statement using the Couchbase JDBC driver.
b) How to retrieve scalar field values from the rows.
*/
public class App {
static String ConnectionURL = "jdbc:couchbase://172.23.123.107:8093";

public static void main(String[] args) throws Exception {
Connection con = DriverManager.getConnection(ConnectionURL);
Statement stmt = con.createStatement();
ResultSet rs = stmt.executeQuery("select a,b from `tsdata` where a = 0 limit 10");
/_ResultSet rs = stmt
.executeQuery("select count as MYCOUNT from `mobile` limit 10");_/
System.out.println("TEN BEERS");
while (rs.next())
{ //String name = rs.getString("name"); double abv = rs.getDouble("MYCOUNT"); //boolean strong = rs.getBoolean("strong"); //System.out.println("name: " + name + ", abv: " + abv + ", strong: " + strong); System.out.println("MYCOUNT: " + abv); }
System.out.println();
/\* rs = stmt.executeQuery("select category, count as num from `tsdata` where type = 'beer' group by category");
System.out.println("BEER CATEGORIES");
while (rs.next())
{ System.out.println(rs.getString("category") + ": " + rs.getInt("num")); }
*/
}
}
}

This works for default and beer-sample on the particular machine.But if I have any other bucket, the connection doesnt work.

Result:
15:29:32.704 [main] INFO  com.couchbase.CBDriver - Constructor called
15:29:32.708 [main] INFO  com.couchbase.CBDriver - Constructor called
Exception in thread "main" java.sql.SQLException: Keyspace not found keyspace tsdata - cause: No bucket named tsdata
    at com.couchbase.jdbc.core.ProtocolImpl.fillSQLException(ProtocolImpl.java:554)
    at com.couchbase.jdbc.core.ProtocolImpl.handleResponse(ProtocolImpl.java:511)
    at com.couchbase.jdbc.core.ProtocolImpl.query(ProtocolImpl.java:331)
    at com.couchbase.CBStatement.executeQuery(CBStatement.java:75)
    at com.test.jdbc.test5.App.main(App.java:19)

Though bucket tsdata exists.

**Comment by arun-gupta** [comment]
This seems like a blocking issue. @j-larson any thoughts?

**Comment by j-larson** [comment]
This is a server-side problem. A RESTful service on the query engine is returning incorrect endpoints. The JDBC driver is trying to contact the Couchbase engine on 127.0.0.1 rather than on 172.23.123.107. We haven't seen this problem before because I have always been testing with my machine on localhost.

Filed as server-side issue MB-18943.

https://issues.couchbase.com/browse/MB-18943

**Comment by j-larson** [comment]
Fixed this in the driver rather than on the server-side.
