### ISSUE TITLE
Passphrase to unlock the secret key for user being asked on mvn clean install

### ISSUE THREAD

**Issue by pm48** [jdbc-json/jdbc-cb#41]
Run mvn clean install and we get this error on screen and a window pops up asking for password of your machine.
You need a passphrase to unlock the secret key for
user: "Prerna Manaktala prerna.manaktala@couchbase.com"
4096-bit RSA key, ID 0B6DA01E, created 2015-08-25

**Comment by j-larson** [comment]
This seems to be a GPG issue, probably an interaction with some of the Maven plugins used for uploading. It should be possible to install locally without supplying a password. Alternately, we need to provide instructions on how to set things up for proper authorization.
